---
- name: Installing httpd
  yum:
    name: httpd
    state: latest
- name: check httpd status
  service:
    name: httpd
    state: started
- replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'Listen 80'
    replace: 'Listen 8000'
    backup: yes

- service:
    name: httpd
    state: reloaded
