---
- name: Installing httpd
  yum:
    name: httpd
    state: latest

- name: changing the port to 8000
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'Listen (8.*)?'
    #replace: '\1Listen 8000'
    replace: 'Listen 8000'
    #replace: 'Listen 8000'
    backup: yes

- name: restarting apache service
  service:
    name: httpd
    state: restarted
